# Ansible Playbook for Subutai readthedocs blueprint
---

- hosts: rtd
  remote_user: root
  tasks:

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Install required debs
      apt:
        name: "{{ item }}"
        state: present
      with_items: 
        - php7.0
        - php7.0-cgi
        - php7.0-mysql
        - apache2
        - libapache2-mod-php7.0
        - unzip 
        - mariadb-server
        - python-mysqldb

    
