# Ansible Playbook for Subutai readthedocs blueprint
---

- hosts: rtd
  remote_user: root
  tasks:

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Install required debs
      apt:
        name: "{{ item }}"
        state: present
      with_items: 
        - software-properties-common
	- bzr
	- subversion
	- git-core
	- mercurial
	- libpq-dev
	- libxml2-dev
	- libxslt-dev
	- libxslt1-dev
	- build-essential
	- postgresql-client
	- libmysqlclient-dev curl 
	- doxygen
	- g++
	- graphviz-dev
	- libfreetype6
	- libbz2-dev
	- libcairo2-dev 
	- libenchant1c2a
	- libevent-dev
	- libffi-dev
	- libfreetype6-dev 
	- libgraphviz-dev
	- libjpeg-dev
	- libjpeg8-dev
	- liblcms2-dev
	- libreadline-dev 
	- libsqlite3-dev
	- libtiff5-dev
	- libwebp-dev
	- pandoc
	- pkg-config
	- zlib1g-dev
	- make
	- libssl-dev
	- wget
	- llvm
	- libncurses5-dev
	- libncursesw5-dev
	- xz-utils
	- tk-dev

